// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type AF struct {
	ID         int64  `json:"id"`
	Numero     int64  `json:"numero"`
	Fornecedor string `json:"fornecedor"`
	Descricao  string `json:"descricao"`
	DataInicio string `json:"data_inicio"`
	DataFim    string `json:"data_fim"`
	Status     bool   `json:"status"`
}

type Item struct {
	ID             int64         `json:"id"`
	AfID           sql.NullInt64 `json:"af_id"`
	LocalID        sql.NullInt64 `json:"local_id"`
	Descricao      string        `json:"descricao"`
	BandaMaxima    int64         `json:"banda_maxima"`
	BandaInstalada int64         `json:"banda_instalada"`
	DataInstalacao string        `json:"data_instalacao"`
}

type Local struct {
	ID   int64  `json:"id"`
	Nome string `json:"nome"`
}

type Log struct {
	ID            int64     `json:"id"`
	ValorAntigo   int64     `json:"valor_antigo"`
	ValorNovo     int64     `json:"valor_novo"`
	DataAlteracao time.Time `json:"data_alteracao"`
}

type Valor struct {
	ID         int64          `json:"id"`
	ItemID     sql.NullInt64  `json:"item_id"`
	Valor      int64          `json:"valor"`
	DataInicio string         `json:"data_inicio"`
	DataFim    sql.NullString `json:"data_fim"`
}
