// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type AF struct {
	ID         int64  `json:"id"`
	Numero     int64  `json:"numero"`
	Fornecedor string `json:"fornecedor"`
	Descricao  string `json:"descricao"`
	DataInicio string `json:"data_inicio"`
	DataFim    string `json:"data_fim"`
	Status     bool   `json:"status"`
}

type Item struct {
	ID             int64  `json:"id"`
	AfID           int64  `json:"af_id"`
	LocalID        int64  `json:"local_id"`
	Descricao      string `json:"descricao"`
	BandaMaxima    int64  `json:"banda_maxima"`
	BandaInstalada int64  `json:"banda_instalada"`
	DataInstalacao string `json:"data_instalacao"`
	Quantidade     int64  `json:"quantidade"`
	Status         bool   `json:"status"`
}

type Local struct {
	ID   int64  `json:"id"`
	Nome string `json:"nome"`
}

type Valor struct {
	ID         int64          `json:"id"`
	ItemID     int64          `json:"item_id"`
	Valor      int64          `json:"valor"`
	DataInicio string         `json:"data_inicio"`
	DataFim    sql.NullString `json:"data_fim"`
}
