CREATE TABLE IF NOT EXISTS AF (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	numero INTEGER NOT NULL UNIQUE,
	fornecedor TEXT NOT NULL,
	descricao TEXT NOT NULL,
	data_inicio DATE NOT NULL,
	data_fim DATE NOT NULL CHECK(data_fim > data_inicio),
	status BOOLEAN NOT NULL
);
