CREATE TABLE Item (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	descricao TEXT NOT NULL,
	banda_maxima INTEGER NOT NULL,
	banda_instalada INTEGER NOT NULL,
	data_instalacao DATE NOT NULL,
	CONSTRAINT Item_PK PRIMARY KEY (id),
	CONSTRAINT Item_AF_FK FOREIGN KEY (id) REFERENCES NewTable(id),
	CONSTRAINT Item_Local_FK FOREIGN KEY (id) REFERENCES "Local"(id)
) STRICT;

