CREATE TABLE Log (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	valor_antigo INTEGER NOT NULL,
	valor_novo INTEGER NOT NULL,
	data_alteracao DATE NOT NULL,
	CONSTRAINT Log_PK PRIMARY KEY (id)
) STRICT;

