CREATE TABLE Valor (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	valor INTEGER NOT NULL,
	data_inicio DATE NOT NULL,
	data_fim DATE,
	CONSTRAINT Valor_PK PRIMARY KEY (id),
	CONSTRAINT Valor_Item_FK FOREIGN KEY (id) REFERENCES Item(id)
) STRICT;

